source 'https://rubygems.org' do
  gem 'sinatra'
  ## NB: on some systems the very latest beta of Sinatra is required:
  #gem 'sinatra', '2.0.0.beta2'
  gem 'thin'
  gem 'capybara'
  gem 'cucumber'
  gem 'rspec'  
  gem 'simplecov'
end